<?php
if ( ! defined( 'ABSPATH' ) ) exit;

$active_tab = isset( $_GET['tab'] ) ? sanitize_text_field( $_GET['tab'] ) : 'export';
?>
<div class="wrap">
    <h1><?php esc_html_e( 'Woo Export Import by CG', 'woo-export-import-by-cg' ); ?></h1>
    
    <?php
    if ( isset( $_GET['error'] ) ) {
        $error = sanitize_text_field( $_GET['error'] );
        if ( 'no_file' === $error ) {
            echo '<div class="notice notice-error"><p>' . esc_html__( 'Please select a file to upload.', 'woo-export-import-by-cg' ) . '</p></div>';
        } elseif ( 'invalid_format' === $error ) {
            echo '<div class="notice notice-error"><p>' . esc_html__( 'Invalid file format. Please upload a valid JSON file generated by this plugin.', 'woo-export-import-by-cg' ) . '</p></div>';
        } elseif ( 'session_expired' === $error ) {
            echo '<div class="notice notice-error"><p>' . esc_html__( 'Session expired. Please upload the file again.', 'woo-export-import-by-cg' ) . '</p></div>';
        }
    }

    if ( isset( $_GET['import'] ) && 'success' === $_GET['import'] ) {
        echo '<div class="notice notice-success is-dismissible"><p>' . esc_html__( 'Import completed successfully.', 'woo-export-import-by-cg' ) . '</p></div>';
    }
    
    if ( isset( $_GET['validate'] ) && 'conflict' === $_GET['validate'] ) {
        $conflicts = get_transient( 'woo_eicg_conflicts_' . get_current_user_id() );
        if ( $conflicts && is_array( $conflicts ) ) {
            foreach ( $conflicts as $conflict ) {
                echo '<div class="notice notice-error"><p>' . wp_kses_post( $conflict ) . '</p></div>';
            }
        }
    }
    
    if ( isset( $_GET['validate'] ) && 'success' === $_GET['validate'] ) {
        echo '<div class="notice notice-success"><p>' . esc_html__( 'Validation passed! No conflicts detected. You can proceed with the import.', 'woo-export-import-by-cg' ) . '</p></div>';
        ?>
        <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
            <input type="hidden" name="action" value="woo_eicg_import">
            <input type="hidden" name="import_action" value="process">
            <?php wp_nonce_field( 'woo_eicg_import_action', 'woo_eicg_import_nonce' ); ?>
            <p><button type="submit" class="button button-primary"><?php esc_html_e( 'Proceed with Import', 'woo-export-import-by-cg' ); ?></button>
               <a href="<?php echo esc_url( admin_url( 'admin.php?page=woo-eicg&tab=import' ) ); ?>" class="button"><?php esc_html_e( 'Cancel', 'woo-export-import-by-cg' ); ?></a>
            </p>
        </form>
        <?php
        return; // Don't show the tabs if we are on the proceed screen
    }
    ?>

    <h2 class="nav-tab-wrapper">
        <a href="?page=woo-eicg&tab=export" class="nav-tab <?php echo 'export' === $active_tab ? 'nav-tab-active' : ''; ?>"><?php esc_html_e( 'Export', 'woo-export-import-by-cg' ); ?></a>
        <a href="?page=woo-eicg&tab=import" class="nav-tab <?php echo 'import' === $active_tab ? 'nav-tab-active' : ''; ?>"><?php esc_html_e( 'Import', 'woo-export-import-by-cg' ); ?></a>
    </h2>

    <div class="tab-content" style="margin-top: 20px;">
        <?php if ( 'export' === $active_tab ) : ?>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
                <input type="hidden" name="action" value="woo_eicg_export">
                <?php wp_nonce_field( 'woo_eicg_export_action', 'woo_eicg_export_nonce' ); ?>
                
                <table class="form-table">
                    <tr>
                        <th scope="row"><?php esc_html_e( 'Select Items to Export', 'woo-export-import-by-cg' ); ?></th>
                        <td>
                            <label><input type="checkbox" name="export_items[]" value="products" checked> <?php esc_html_e( 'Products', 'woo-export-import-by-cg' ); ?></label><br>
                            <label><input type="checkbox" name="export_items[]" value="customers" checked> <?php esc_html_e( 'Customers', 'woo-export-import-by-cg' ); ?></label><br>
                            <label><input type="checkbox" name="export_items[]" value="orders" checked> <?php esc_html_e( 'Orders', 'woo-export-import-by-cg' ); ?></label>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><?php esc_html_e( 'Date Range (Optional)', 'woo-export-import-by-cg' ); ?></th>
                        <td>
                            <label for="start_date"><?php esc_html_e( 'Start Date:', 'woo-export-import-by-cg' ); ?></label>
                            <input type="date" id="start_date" name="start_date">
                            <label for="end_date" style="margin-left: 20px;"><?php esc_html_e( 'End Date:', 'woo-export-import-by-cg' ); ?></label>
                            <input type="date" id="end_date" name="end_date">
                            <p class="description"><?php esc_html_e( 'Leave empty to export all records.', 'woo-export-import-by-cg' ); ?></p>
                        </td>
                    </tr>
                </table>
                <p class="submit">
                    <button type="submit" class="button button-primary"><?php esc_html_e( 'Export Data', 'woo-export-import-by-cg' ); ?></button>
                </p>
            </form>
        <?php elseif ( 'import' === $active_tab ) : ?>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" enctype="multipart/form-data">
                <input type="hidden" name="action" value="woo_eicg_import">
                <input type="hidden" name="import_action" value="validate">
                <?php wp_nonce_field( 'woo_eicg_import_action', 'woo_eicg_import_nonce' ); ?>
                
                <table class="form-table">
                    <tr>
                        <th scope="row"><?php esc_html_e( 'Upload File', 'woo-export-import-by-cg' ); ?></th>
                        <td>
                            <input type="file" name="import_file" accept=".json" required>
                            <p class="description"><?php esc_html_e( 'Upload the JSON file generated by this plugin. We will validate it for conflicts before importing.', 'woo-export-import-by-cg' ); ?></p>
                        </td>
                    </tr>
                </table>
                <p class="submit">
                    <button type="submit" class="button button-primary"><?php esc_html_e( 'Validate & Import', 'woo-export-import-by-cg' ); ?></button>
                </p>
            </form>
        <?php endif; ?>
    </div>
</div>
